# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d13eea8a35e90f32d8dea4ff616bad1dac744dcd8d675e15bca8b62149d07733af513723196e30053ca9d3f7c545c4832e19b78b18c5c6dbf6b055d63556d4a6

test:
  secret_key_base: bfd8f4974a5bc251fb468c60a20a35264680756abb117e0ae9d1f140bb7d37f0bb3b6fbe84530352d245c0173577f506b68a0e59edcf3cfa93fbd6c92718ad73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
